language: ruby
rvm:
  - 2.2.3
before_install: gem install bundler -v 1.10.6

services:
  - postgresql

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - "rake db:drop RAILS_ENV=test"
  - "rake db:setup RAILS_ENV=test"
