# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

# book1 = Book.create(title: "The Universe in a Nutshell", description: "The Universe in a Nutshell is one of Stephen Hawking's books on theoretical physics. It explains to a general audience various matters relating to the Lucasian professor's work, such as Gödel's Incompleteness Theorem and P-branes (part of superstring theory in quantum mechanics).", price: 8.99, quantity_in_stock: 33)
# book2 = Book.create(title: "A Brief History of Time", description: "Is a 1988 popular-science book by British physicist Stephen Hawking. It became a bestseller and sold more than 10 million copies in 20 years. It was also on the London Sunday Times bestseller list for more than four years and was translated into 35 languages by 2001", price: 9.99, quantity_in_stock: 25)
# book3 = Book.create(title: "On The Shoulders of Giants", description: "On the Shoulders of Giants is a compilation of scientific texts edited and with commentary by the British theoretical physicist Stephen Hawking.", price: 9.99, quantity_in_stock: 50)
# book4 = Book.create(title: "My Brief History", description: "My Brief History is a memoir published in 2013 by the English physicist Stephen Hawking. The book recounts Hawkins journey from his post-war London boyhood to his years of international acclaim and celebrity.", price: 7.50 , quantity_in_stock:12 )
# book5 = Book.create(title: "Black Holes and Baby Universes and other Essays", description: "This book is a collection of essays and lectures written by Hawking, mainly about the makeup of black holes, and why they might be nodes from which other universes grow.", price: 15 , quantity_in_stock: 44)
# book6 = Book.create(title: "The Selfish Gene", description: "The Selfish Gene is a book on evolution by Richard Dawkins, published in 1976. It builds upon the principal theory of George C. Williams's first book Adaptation and Natural Selection.", price: 7.49, quantity_in_stock: 67)
# book7 = Book.create(title: "The Extended Phenotype", description: "The Extended Phenotype is a 1982 book by Richard Dawkins in which he introduced a biological concept of the same name. The main idea is that phenotype should not be limited to biological processes such as protein biosynthesis or tissue growth, but extended to include all effects that a gene has on its environment, inside or outside the body of the individual organism.", price: 11, quantity_in_stock: 11)
# book8 = Book.create(title: "The Blind Watchmaker", description: "The Blind Watchmaker: Why the Evidence of Evolution Reveals a Universe without Design is a 1986 book by Richard Dawkins in which he presents an explanation of, and argument for, the theory of evolution by means of natural selection.", price: 11.2, quantity_in_stock: 12)
# book9 = Book.create(title: "River Out of Eden", description: "River Out of Eden: A Darwinian View of Life is a 1995 popular science book by Richard Dawkins. The book is about Darwinian evolution and includes summaries of the topics covered in his earlier books, The Selfish Gene, The Extended Phenotype and The Blind Watchmaker.", price: 10.99, quantity_in_stock: 2)
# book10 = Book.create(title: "The God Delusion", description: "In The God Delusion, Dawkins contends that a supernatural creator almost certainly does not exist and that belief in a personal god qualifies as a delusion, which he defines as a persistent false belief held in the face of strong contradictory evidence.", price: 53.78, quantity_in_stock: 5)
# book11 = Book.create(title: "", description: "", price: 25,3, quantity_in_stock: 10)
# book12 = Book.create(title: "", description: "", price: 32,72, quantity_in_stock: 7)

Author.create([
  { firstname: "Stephen", lastname: "Hawking", biography: "Stephen William Hawking (born 8 January 1942) is an English theoretical physicist, cosmologist, author and Director of Research at the Centre for Theoretical Cosmology within the University of Cambridge." },
  { firstname: "Richard", lastname: "Dawkins", biography: "Clinton Richard Dawkins (born 26 March 1941) is an English ethologist, evolutionary biologist, and writer. He is an emeritus fellow of New College, Oxford, and was the University of Oxford's Professor for Public Understanding of Science from 1995 until 2008." },
  { firstname: "David", lastname: "Flanagan", biography: "David Flanagan is a computer programmer who has spent much of the last 20 years writing books about programming languages. He now works at Mozilla. David lives with his wife and children in the Pacific Northwest, between the cities of Seattle and Vancouver." },
  { firstname: "Yukihiro", lastname: "Matsumoto", biography: "Yukihiro Matsumoto (松本行弘 (まつもとゆきひろ) Matsumoto Yukihiro, a.k.a. Matz, born 14 April 1965) is a Japanese computer scientist and software programmer best known as the chief designer of the Ruby programming language and its reference implementation, Matz's Ruby Interpreter (MRI). His demeanor has brought about a motto in the Ruby community 'Matz is nice and so we are nice,' commonly abbreviated as MINASWAN." },
  { firstname: "Chris", lastname: "Pine", biography: "" },
  { firstname: "Michael", lastname: "Hartl", biography: "" },
  { firstname: "Sam", lastname: "Ruby", biography: "" },
  { firstname: "Dave", lastname: "Thomas", biography: "" },
  { firstname: "David", lastname: "Heinemeier Hansson", biography: "" },
  { firstname: "Paolo", lastname: "Perrotta", biography: "" }
  ])

Category.create([
  { title: "Physics" },
  { title: "Biology" },
  { title: "Programming" }
  ])

Book.create([
  { title: "The Universe in a Nutshell", description: "The Universe in a Nutshell is one of Stephen Hawking's books on theoretical physics. It explains to a general audience various matters relating to the Lucasian professor's work, such as Gödel's Incompleteness Theorem and P-branes (part of superstring theory in quantum mechanics).", price: 8.99, quantity_in_stock: 33, category_id: 1, author_ids: [1] },
  { title: "A Brief History of Time", description: "Is a 1988 popular-science book by British physicist Stephen Hawking. It became a bestseller and sold more than 10 million copies in 20 years. It was also on the London Sunday Times bestseller list for more than four years and was translated into 35 languages by 2001", price: 9.99, quantity_in_stock: 25, category_id: 1, author_ids: [1] },
  { title: "On The Shoulders of Giants", description: "On the Shoulders of Giants is a compilation of scientific texts edited and with commentary by the British theoretical physicist Stephen Hawking.", price: 9.99, quantity_in_stock: 50, category_id: 1, author_ids: [1] },
  { title: "My Brief History", description: "My Brief History is a memoir published in 2013 by the English physicist Stephen Hawking. The book recounts Hawkins journey from his post-war London boyhood to his years of international acclaim and celebrity.", price: 7.50 , quantity_in_stock:12, category_id: 1, author_ids: [1] },
  { title: "Black Holes and Baby Universes and other Essays", description: "This book is a collection of essays and lectures written by Hawking, mainly about the makeup of black holes, and why they might be nodes from which other universes grow.", price: 15 , quantity_in_stock: 44, category_id: 1, author_ids: [1] },
  { title: "The Selfish Gene", description: "The Selfish Gene is a book on evolution by Richard Dawkins, published in 1976. It builds upon the principal theory of George C. Williams's first book Adaptation and Natural Selection.", price: 7.49, quantity_in_stock: 67, category_id: 2, author_ids: [2] },
  { title: "The Extended Phenotype", description: "The Extended Phenotype is a 1982 book by Richard Dawkins in which he introduced a biological concept of the same name. The main idea is that phenotype should not be limited to biological processes such as protein biosynthesis or tissue growth, but extended to include all effects that a gene has on its environment, inside or outside the body of the individual organism.", price: 11, quantity_in_stock: 11, category_id: 2, author_ids: [2] },
  { title: "The Blind Watchmaker", description: "The Blind Watchmaker: Why the Evidence of Evolution Reveals a Universe without Design is a 1986 book by Richard Dawkins in which he presents an explanation of, and argument for, the theory of evolution by means of natural selection.", price: 11.2, quantity_in_stock: 12, category_id: 2, author_ids: [2] },
  { title: "River Out of Eden", description: "River Out of Eden: A Darwinian View of Life is a 1995 popular science book by Richard Dawkins. The book is about Darwinian evolution and includes summaries of the topics covered in his earlier books, The Selfish Gene, The Extended Phenotype and The Blind Watchmaker.", price: 10.99, quantity_in_stock: 2, category_id: 2, author_ids: [2] },
  { title: "The God Delusion", description: "In The God Delusion, Dawkins contends that a supernatural creator almost certainly does not exist and that belief in a personal god qualifies as a delusion, which he defines as a persistent false belief held in the face of strong contradictory evidence.", price: 53.78, quantity_in_stock: 5, category_id: 2, author_ids: [2] },
  { title: "The Ruby Programming Language", description: "The Ruby Programming Language is the authoritative guide to Ruby and provides comprehensive coverage of versions 1.8 and 1.9 of the language. It was written (and illustrated!) by an all-star team. David Flanagan, bestselling author of programming language 'bibles' (including JavaScript: The Definitive Guide and Java in a Nutshell) and committer to the Ruby Subversion repository. Yukihiro 'Matz' Matsumoto, creator, designer and lead developer of Ruby and author of Ruby in a Nutshell, which has been expanded and revised to become this book, why the lucky stiff, artist and Ruby programmer extraordinaire.", price: 23.99, quantity_in_stock: 42, category_id: 3, author_ids: [3, 4] },
  { title: "Learn to Program, Second Edition (The Facets of Ruby Series)", description: "For this new edition of the best-selling Learn to Program, Chris Pine has taken a good thing and made it even better. First, he used the feedback from hundreds of reader e-mails to update the content and make it even clearer. Second, he updated the examples in the book to use the latest stable version of Ruby, and also to use code that looks more like real-world Ruby code, so that people who have just learned to program will be more familiar with common Ruby techniques. ", price: 12, quantity_in_stock: 11, category_id: 3, author_ids: [5] },
  { title: "Ruby on Rails Tutorial: Learn Web Development with Rails", description: "Used by sites as diverse as Twitter, GitHub, Disney, and the Yellow Pages, Ruby on Rails is one of the most popular frameworks for developing web applications, but it can be challenging to learn and use. Whether you’re new to web development or new only to Rails, Ruby on Rails™ Tutorial, is the solution.", price: 29.84, quantity_in_stock: 20, category_id: 3, author_ids: [6] },
  { title: "Agile Web Development with Rails 4", description: "Rails just keeps on changing. Both Rails 3 and 4, as well as Ruby 1.9 and 2.0, bring hundreds of improvements, including new APIs and substantial performance enhancements. The fourth edition of this award-winning classic has been reorganized and refocused so it's more useful than ever before for developers new to Ruby and Rails. Rails 4 introduces a number of user-facing changes, and the ebook has been updated to match all the latest changes and new best practices in Rails. This includes full support for Ruby 2.0, controller concerns, Russian Doll caching, strong parameters, Turbolinks, new test and bin directory layouts, and much more.", price: 28.41, quantity_in_stock: 23, category_id: 3, author_ids: [7, 8, 9] },
  { title: "Metaprogramming Ruby: Program Like the Ruby Pros", description: "Everyone in the Ruby world seems to be talking about metaprogramming--how you can use it to remove duplication in your code and write elegant, beautiful programs. Now you can get in on the action as well. This book describes metaprogramming as an essential component of Ruby. Once you understand the principles of Ruby, including the object model, scopes, and eigenclasses, you're on your way to applying metaprogramming both in your daily work and in your fun, after-hours projects.", price: 27.45, quantity_in_stock: 5, category_id: 3, author_ids: [10] }
  ])




countries = ["Andorra",
"United Arab Emirates",
"Afghanistan",
"Antigua and Barbuda",
"Anguilla",
"Albania",
"Armenia",
"Angola",
"Antarctica",
"Argentina",
"American Samoa",
"Austria",
"Australia",
"Aruba",
"Aland Islands",
"Azerbaijan",
"Bosnia and Herzegovina",
"Barbados",
"Bangladesh",
"Belgium",
"Burkina Faso",
"Bulgaria",
"Bahrain",
"Burundi",
"Benin",
"Saint Barthelemy",
"Bermuda",
"Brunei",
"Bolivia",
"Bonaire, Saint Eustatius and Saba ",
"Brazil",
"Bahamas",
"Bhutan",
"Bouvet Island",
"Botswana",
"Belarus",
"Belize",
"Canada",
"Cocos Islands",
"Democratic Republic of the Congo",
"Central African Republic",
"Republic of the Congo",
"Switzerland",
"Ivory Coast",
"Cook Islands",
"Chile",
"Cameroon",
"China",
"Colombia",
"Costa Rica",
"Cuba",
"Cape Verde",
"Curacao",
"Christmas Island",
"Cyprus",
"Czech Republic",
"Germany",
"Djibouti",
"Denmark",
"Dominica",
"Dominican Republic",
"Algeria",
"Ecuador",
"Estonia",
"Egypt",
"Western Sahara",
"Eritrea",
"Spain",
"Ethiopia",
"Finland",
"Fiji",
"Falkland Islands",
"Micronesia",
"Faroe Islands",
"France",
"Gabon",
"United Kingdom",
"Grenada",
"Georgia",
"French Guiana",
"Guernsey",
"Ghana",
"Gibraltar",
"Greenland",
"Gambia",
"Guinea",
"Guadeloupe",
"Equatorial Guinea",
"Greece",
"South Georgia and the South Sandwich Islands",
"Guatemala",
"Guam",
"Guinea-Bissau",
"Guyana",
"Hong Kong",
"Heard Island and McDonald Islands",
"Honduras",
"Croatia",
"Haiti",
"Hungary",
"Indonesia",
"Ireland",
"Israel",
"Isle of Man",
"India",
"British Indian Ocean Territory",
"Iraq",
"Iran",
"Iceland",
"Italy",
"Jersey",
"Jamaica",
"Jordan",
"Japan",
"Kenya",
"Kyrgyzstan",
"Cambodia",
"Kiribati",
"Comoros",
"Saint Kitts and Nevis",
"North Korea",
"South Korea",
"Kosovo",
"Kuwait",
"Cayman Islands",
"Kazakhstan",
"Laos",
"Lebanon",
"Saint Lucia",
"Liechtenstein",
"Sri Lanka",
"Liberia",
"Lesotho",
"Lithuania",
"Luxembourg",
"Latvia",
"Libya",
"Morocco",
"Monaco",
"Moldova",
"Montenegro",
"Saint Martin",
"Madagascar",
"Marshall Islands",
"Macedonia",
"Mali",
"Myanmar",
"Mongolia",
"Macao",
"Northern Mariana Islands",
"Martinique",
"Mauritania",
"Montserrat",
"Malta",
"Mauritius",
"Maldives",
"Malawi",
"Mexico",
"Malaysia",
"Mozambique",
"Namibia",
"New Caledonia",
"Niger",
"Norfolk Island",
"Nigeria",
"Nicaragua",
"Netherlands",
"Norway",
"Nepal",
"Nauru",
"Niue",
"New Zealand",
"Oman",
"Panama",
"Peru",
"French Polynesia",
"Papua New Guinea",
"Philippines",
"Pakistan",
"Poland",
"Saint Pierre and Miquelon",
"Pitcairn",
"Puerto Rico",
"Palestinian Territory",
"Portugal",
"Palau",
"Paraguay",
"Qatar",
"Reunion",
"Romania",
"Serbia",
"Russia",
"Rwanda",
"Saudi Arabia",
"Solomon Islands",
"Seychelles",
"Sudan",
"Sweden",
"Singapore",
"Saint Helena",
"Slovenia",
"Svalbard and Jan Mayen",
"Slovakia",
"Sierra Leone",
"San Marino",
"Senegal",
"Somalia",
"Suriname",
"Sao Tome and Principe",
"El Salvador",
"Sint Maarten",
"Syria",
"Swaziland",
"Turks and Caicos Islands",
"Chad",
"French Southern Territories",
"Togo",
"Thailand",
"Tajikistan",
"Tokelau",
"East Timor",
"Turkmenistan",
"Tunisia",
"Tonga",
"Turkey",
"Trinidad and Tobago",
"Tuvalu",
"Taiwan",
"Tanzania",
"Ukraine",
"Uganda",
"United States Minor Outlying Islands",
"United States",
"Uruguay",
"Uzbekistan",
"Vatican",
"Saint Vincent and the Grenadines",
"Venezuela",
"British Virgin Islands",
"U.S. Virgin Islands",
"Vietnam",
"Vanuatu",
"Wallis and Futuna",
"Samoa",
"Yemen",
"Mayotte",
"South Africa",
"Zambia",
"Zimbabwe",
"Serbia and Montenegro",
"Netherlands Antilles"]

countries.each do |name|
  Country.create({name: name})
end
